
# ==== Void Spectra colors ====

color0 #3b434d
color1 #eb0000
color2 #00eb07
color3 #eb8700
color4 #006ceb
color5 #7900eb
color6 #00beeb
color7 #768699
color8 #4f565f
color9 #ff1414
color10 #18ff1f
color11 #ff9f14
color12 #147eff
color13 #9514ff
color14 #14d2ff
color15 #9db3cc

cursor                #9db3cc
cursor_text_color     #161616
background            #181818
foreground            #c4e0ff
selection_foreground  #9db3cc
selection_background  #2f2f2f
active_border_color   #eb8700
inactive_border_color #2d2d2d
url_color             #eb8700

active_tab_foreground   #181818
active_tab_background   #eb8700
inactive_tab_foreground #9aa5ce
inactive_tab_background #2d2d2d
cursor_trail_color      #9aa5ce

