hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("GTK_USE_PORTAL", "1")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ZF_COLORS", "--color='spinner:#f5e0dc,hl:#f089b6' --color='fg:#f2f4f8,header:#f089b6,info:#76d191,pointer:#f5e0dc' --color='marker:#b2b5ff,fg+:#f2f4f8,prompt:#76d191,hl+:#f089b6' --color='selected-bg:#393939' --color='border:#6f6f6f,label:#f2f4f8'")
