if hl.plugin.hyprcapture then
  hl.config({
    plugin = {
      hyprcapture = {
        default_mode = "region",
        fullscreen_scope = "all",
        overlay_scope = "fix",
        window_background = "follow-system",
        window_border = "keep",
        window_shadow = "keep",
        notification_backend = "hyprland",
        save = true,
        clipboard = true,
        show_thumbnail = false,
        allow_quick = false,
        confirm_before_capture = false,
        fusion_mode = true,
        capture_fullscreen_clients_as_monitor = false,
        dynamic_window_metadata = true,
        fullscreen_preview_rounding = "auto",
        save_dir = "~/Screenshots",
        filename_template = "Screenshot-%Y-%m-%d-%H%M%S.jpg",
        record_save_dir = "$XDG_VIDEOS_DIR/Screenrecords",
        record_filename_template = "Recording-%Y-%m-%d-%H%M%S.mp4",
        record_format = "mp4",
        record_transparent_format = "webm",
        record_fps = 30,
        record_fps_options = "15 24 30 60",
        record_window_fps_limit = 12,
        record_window_real_bg_fps_limit = 8,
        record_codec = "libx264",
        record_transparent_codec = "auto",
        record_solid_alpha = false,
        record_preset = "veryfast",
        record_gsr_flags = "",
        record_window_backend = "compositor",
        record_max_seconds = 0,
        record_countdown_seconds = 0,
        include_cursor = true,
        thumbnail_timeout_ms = 5000,
        thumbnail_monitor = "active",
        watermark = "",
        watermark_position = "central",
        watermark_width = "20%",
        watermark_offset = "0 0",
      },
    },
  })

end
