[templates.nvim-base16]
input_path = "~/.config/nvim/lua/matugen-template.lua"
output_path = "~/.config/nvim/lua/matugen.lua"
post_hook = 'pkill -SIGUSR1 nvim'

[templates.hyprland-lua]
input_path = "~/.config/hypr/noctalia/noctalia-template.lua"
output_path = "~/.config/hypr/noctalia/noctalia-colors.lua"
post_hook = 'hypctl reload'
