foreground #828282
background #111111
#background #191919
selection_foreground #111111
selection_background #828282
cursor #aaaaaa
cursor_text_color #111111

scrollbar_handle_color #3c3c3c
scrollbar_track_color #191919
url_color #cccccc

active_border_color #aaaaaa
inactive_border_color #191919
bell_border_color #dddddd

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #111111
active_tab_background #aaaaaa
inactive_tab_foreground #828282
inactive_tab_background #191919
tab_bar_background #111111

mark1_foreground #111111
mark1_background #aaaaaa
mark2_foreground #111111
mark2_background #cccccc
mark3_foreground #111111
mark3_background #a7a7a7

# normal
color0 #191919
color1 #dddddd
color2 #cccccc
color3 #aaaaaa
color4 #a7a7a7
color5 #dddddd
color6 #cccccc
color7 #828282

# bright
color8 #3c3c3c
color9 #dddddd
color10 #cccccc
color11 #aaaaaa
color12 #a7a7a7
color13 #dddddd
color14 #cccccc
color15 #ffffff
