foreground #f2f4f8
background #151515
#background #0F0F0F
selection_foreground #f2f4f8
selection_background #393939
cursor #f2f4f8
cursor_text_color #161616

scrollbar_handle_color #8d8d8d
scrollbar_track_color #161616
url_color #f5e0dc

active_border_color #b2b5ff
inactive_border_color #525252
bell_border_color #fde391

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #161616
active_tab_background #cca9ff
inactive_tab_foreground #f2f4f8
inactive_tab_background #161616
tab_bar_background #0c0c0c

mark1_foreground #161616
mark1_background #5e95ff
mark2_foreground #161616
mark2_background #cca9ff
mark3_foreground #161616
mark3_background #60bcf7

color0 #525252
color8 #6f6f6f
color1 #e35861
color9 #fa7a81
color2 #76d191
color10 #76d191
color3 #fde391
color11 #fde391
color4 #5e95ff
color12 #7baaff
color5 #ffa2c9
color13 #f089b6
color6 #60bcf7
color14 #9cc2ff
color7 #dde1e6
color15 #f2f4f8

