foreground #c0caf5
background #1a1b26
#background #16161e
selection_foreground #c0caf5
selection_background #33467c
cursor #c0caf5
cursor_text_color #1a1b26

scrollbar_handle_color #565f89
scrollbar_track_color #16161e
url_color #ff9e64

active_border_color #7aa2f7
inactive_border_color #444b6a
bell_border_color #e0af68

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground #1a1b26
active_tab_background #9d7cd8
inactive_tab_foreground #c0caf5
inactive_tab_background #16161e
tab_bar_background #101014

mark1_foreground #1a1b26
mark1_background #7aa2f7
mark2_foreground #1a1b26
mark2_background #9d7cd8
mark3_foreground #1a1b26
mark3_background #73daca

color0 #444b6a
color8 #565f89
color1 #f7768e
color9 #ff5577
color2 #9ece6a
color10 #9ece6a
color3 #e0af68
color11 #e0af68
color4 #7aa2f7
color12 #89ddff
color5 #bb9af7
color13 #b4f9f8
color6 #73daca
color14 #2ac3de
color7 #a9b1d6
color15 #c0caf5
