function conf-sudo
    set tmp_sudoers (mktemp)
    set sudoers_file "/etc/sudoers.d/99_custom_defaults"

    set config_lines \
    'Defaults!/usr/bin/visudo env_keep += "SUDO_EDITOR EDITOR VISUAL"' \
    'Defaults pwfeedback' \
    'Defaults timestamp_timeout=10' \
    'Defaults passprompt=" Access restricted: "' \
    'Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/bin"'

    sudo cat /etc/sudoers > $tmp_sudoers
    for line in $config_lines
        echo $line >> $tmp_sudoers
    end

    if sudo visudo -cf $tmp_sudoers >/dev/null 2>&1
        echo "# Generated by script" | sudo tee $sudoers_file >/dev/null
        for line in $config_lines
            echo $line | sudo tee -a $sudoers_file >/dev/null
        end
        sudo chmod 0440 $sudoers_file
        printf "\e[1A\e[2K"
        echo -n "Success."
    else
        echo "Error: Syntax check failed."
    end

    rm -f $tmp_sudoers
end
