general {
    lock_cmd = pidof hyprlock || hyprlock       # замок
    before_sleep_cmd = loginctl lock-session    # лочим ДО сна
    after_sleep_cmd = hyprctl dispatch dpms on  # ПИНАЕМ МОНИТОР ПРИ ПРОСЫПАНИИ
}

listener {
    timeout = 900                                # 15 минут бездействия
    on-timeout = loginctl lock-session           # лочим по таймеру
}
