$rosewater = rgb(f5e0dc)
$rosewaterAlpha = f5e0dc

$flamingo = rgb(f089b6)
$flamingoAlpha = f089b6

$pink = rgb(ffa2c9)
$pinkAlpha = ffa2c9

$mauve = rgb(cca9ff)
$mauveAlpha = cca9ff

$red = rgb(fa7a81)
$redAlpha = fa7a81

$maroon = rgb(e35861)
$maroonAlpha = e35861

$peach = rgb(ffa466)
$peachAlpha = ffa466

$yellow = rgb(fde391)
$yellowAlpha = fde391

$green = rgb(76d191)
$greenAlpha = 76d191

$teal = rgb(60bcf7)
$tealAlpha = 60bcf7

$sky = rgb(9cc2ff)
$skyAlpha = 9cc2ff

$sapphire = rgb(7baaff)
$sapphireAlpha = 7baaff

$blue = rgb(5e95ff)
$blueAlpha = 5e95ff

$lavender = rgb(b2b5ff)
$lavenderAlpha = b2b5ff

$text = rgb(f2f4f8)
$textAlpha = f2f4f8

$subtext1 = rgb(f2f4f8)
$subtext1Alpha = f2f4f8

$subtext0 = rgb(dde1e6)
$subtext0Alpha = dde1e6

$overlay2 = rgb(c6c6c6)
$overlay2Alpha = c6c6c6

$overlay1 = rgb(a8a8a8)
$overlay1Alpha = a8a8a8

$overlay0 = rgb(8d8d8d)
$overlay0Alpha = 8d8d8d

$surface2 = rgb(6f6f6f)
$surface2Alpha = 6f6f6f

$surface1 = rgb(525252)
$surface1Alpha = 525252

$surface0 = rgb(393939)
$surface0Alpha = 393939

$base = rgb(161616)
$baseAlpha = 161616

$mantle = rgb(262626)
$mantleAlpha = 262626

$crust = rgb(0c0c0c)
$crustAlpha = 0c0c0c
